server:
  port: 8009
spring:
  datasource:
    url: jdbc:mysql://172.18.21.168:3306/xmjg_agcloud_1104?characterEncoding=utf-8\
      &allowMultiQueries=true&zeroDateTimeBehavior=convertToNull\
      &useSSL=false&allowPublicKeyRetrieval=true\
      &serverTimezone=Asia/Shanghai
    username: xmjg_agcloud
    password: xmjg_agcloud
    driver-class-name: com.mysql.jdbc.Driver
sso:
  security:
    successUrl: http://www.baidu.com