server:
  port: 8009
spring:
  datasource:
    url: jdbc:mysql://192.168.0.110:3308/testdb?characterEncoding=utf-8\
      &allowMultiQueries=true&zeroDateTimeBehavior=convertToNull\
      &useSSL=false&allowPublicKeyRetrieval=true\
      &serverTimezone=Asia/Shanghai
    username: root
    password: loveQueena1991
    driver-class-name: com.mysql.cj.jdbc.Driver

sso:
  security:
    successUrl: http://www.baidu.com